.common-values:
  docker-image: circleci/python:3.6
  working_directory: ~/repo
  restore-cache:
    keys:
    - v1-dependencies-{{ checksum "requirements.txt" }}
    - v1-dependencies-
  create-venv:
    name: Create virtualenv
    command: |
      /usr/local/bin/python3 -m venv venv
  save-cache:
    paths:
    - ./venv
    key: v1-dependencies-{{ checksum "requirements.txt" }}
.lint-steps:
  docker:
  - image: circleci/python:3.6
  working_directory: ~/repo
  steps:
  - checkout
  - restore_cache:
      keys:
      - v1-dependencies-{{ checksum "requirements.txt" }}
      - v1-dependencies-
  - run:
      name: Create virtualenv
      command: |
        /usr/local/bin/python3 -m venv venv
  - run:
      name: Check code style (PEP8)
      command: |
        . venv/bin/activate
        venv/bin/python3 -m pip install flake8
        venv/bin/python3 -m flake8 \
          --ignore=E731,W503 \
          --filename=*.py \
          --exclude=__init__.py \
          --show-source \
          --statistics \
          --max-line-length=120 \
          src/ tests/
  - save_cache:
      paths:
      - ./venv
      key: v1-dependencies-{{ checksum "requirements.txt" }}
.build-and-test-steps:
  docker:
  - image: circleci/python:3.6
  working_directory: ~/repo
  steps:
  - checkout
  - restore_cache:
      keys:
      - v1-dependencies-{{ checksum "requirements.txt" }}
      - v1-dependencies-
  - run:
      name: Create virtualenv
      command: |
        /usr/local/bin/python3 -m venv venv
  - save_cache:
      paths:
      - ./venv
      key: v1-dependencies-{{ checksum "requirements.txt" }}
  - run:
      name: Install package
      command: |
        . venv/bin/activate
        venv/bin/python3 -m pip install -e .[test_deps]
  - run:
      name: Run tests
      command: |
        . venv/bin/activate
        venv/bin/python3 -m pytest --cov=pycst tests/
.pip-check:
  docker:
  - image: circleci/python:3.6
  working_directory: ~/repo
  steps:
  - checkout
  - restore_cache:
      keys:
      - v1-dependencies-{{ checksum "requirements.txt" }}
      - v1-dependencies-
  - run:
      name: Create virtualenv
      command: |
        /usr/local/bin/python3 -m venv venv
  - save_cache:
      paths:
      - ./venv
      key: v1-dependencies-{{ checksum "requirements.txt" }}
  - run:
      name: Run pip check
      command: |
        . venv/bin/activate
        sudo venv/bin/python -m pip install -e .
        pip check
version: 2
jobs:
  lint:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: Create virtualenv
        command: |
          /usr/local/bin/python3 -m venv venv
    - run:
        name: Check code style (PEP8)
        command: |
          . venv/bin/activate
          venv/bin/python3 -m pip install flake8
          venv/bin/python3 -m flake8 \
            --ignore=E731,W503 \
            --filename=*.py \
            --exclude=__init__.py \
            --show-source \
            --statistics \
            --max-line-length=120 \
            src/ tests/
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
  build-and-test:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: Create virtualenv
        command: |
          /usr/local/bin/python3 -m venv venv
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - run:
        name: Install package
        command: |
          . venv/bin/activate
          venv/bin/python3 -m pip install -e .[test_deps]
    - run:
        name: Run tests
        command: |
          . venv/bin/activate
          venv/bin/python3 -m pytest --cov=pycst tests/
  pip-check:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: Create virtualenv
        command: |
          /usr/local/bin/python3 -m venv venv
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - run:
        name: Run pip check
        command: |
          . venv/bin/activate
          sudo venv/bin/python -m pip install -e .
          pip check
workflows:
  version: 2
  build-and-test-all:
    jobs:
    - lint
    - build-and-test:
        context: python-projects
    - pip-check:
        context: python-projects
