.common-values:
  docker-image: &docker-image winamd64/python:3.7
  working_directory: &working-directory ~/repo

  # Download and cache dependencies
  restore-cache: &restore-cache
    keys:
    - v1-dependencies-{{ checksum "requirements.txt" }}
    # fallback to using the latest cache if no exact match is found
    - v1-dependencies-

  save-cache: &save-cache
    paths:
    - ./venv
    key: v1-dependencies-{{ checksum "requirements.txt" }}


.lint-steps: &lint-steps
  docker:
  - image: *docker-image
  working_directory: *working-directory
  steps:
  - checkout
  - restore_cache: *restore-cache
  - run: *create-venv
  - run:
      name: Check code style (PEP8)
      command: |
        python -m pip install flake8
        python -m flake8 \
          --ignore=E731,W503 \
          --filename=*.py \
          --exclude=__init__.py \
          --show-source \
          --statistics \
          --max-line-length=120 \
          src/ tests/
  - save_cache: *save-cache

version: 2
jobs:
  lint:
    <<: *lint-steps


workflows:
  version: 2
  build:
    jobs:
    - lint

